# Slack webhooks for notifications
# Possibly load these via os.environ or the CLI.
posting_webhook = ""
errorlogging_webhook = ""

# crtsh postgres credentials, please leave it unchanged.
DB_HOST = 'crt.sh'
DB_NAME = 'certwatch'
DB_USER = 'guest'
DB_PASSWORD = ''